server:
  port: 8080

spring:
  application:
    name: gateway

  data:
    redis: # Redis Configuration
      host: localhost
      port: 6379
      database: 0
      timeout: 60000

  cloud:
    gateway:
      redis-rate-limiter: # rate limiter config
        replenish-rate: 4
        burst-capability: 80
        requested-tokens: 1