services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=rustRetail'
      - 'POSTGRES_PASSWORD=123456'
      - 'POSTGRES_USER=root'
    ports:
      - '5432'
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=123456'
      - 'RABBITMQ_DEFAULT_USER=root'
    ports:
      - '5672'
